# Generated by Django 5.1.3 on 2024-12-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_disease_ingredient_meal_mealingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
